query GetProductById($getProductByIdId: Int!) {
  getProductById(id: $getProductByIdId) {
    description
    id
    name
    picture
    price
    growtype
    origin
    potency
    straintype
    taste
  }
}
