name: Test, compile and push client and server to production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-client:
    uses: ricardomrcruz/graphql_crud/.github/workflows/tests-front.yml@main

  integration-tests:
    uses: ricardomrcruz/graphql_crud/.github/workflows/integration-tests.yml@main

  build-and-push-server:
    needs:
      - integration-tests
    uses: ricardomrcruz/graphql_crud/.github/workflows/build-backend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: ricardomcrvz/cbdshop-back

  build-and-push-client:
    needs:
      - test-client
    uses: ricardomrcruz/graphql_crud/.github/workflows/build-frontend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: ricardomcrvz/cbdshop-front
